version: "3"
services:
  backend:
    container_name: flask
    build: 
      context: .
    ports:
      - 80:8080
    depends_on:
      - db
    volumes:
      - ./:/app
  db: 
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_hosts
    ports: 
      - "36000:3306"
    volumes:
      - ./db:/var/lib/mysql
